### ISSUE TITLE
Show the next event content.

### ISSUE THREAD

**Issue by Unisergius** [onelikeandidie/meetballs.org#2]
Title, Description, image if any. 

As a card or as hero content.

To discuss

**Comment by onelikeandidie** [comment]
You mean like as a featured card? Like highlighted? With a forum or something?

**Comment by Unisergius** [comment]
Just featured. No comments.
Is it a good idea?

**Comment by onelikeandidie** [comment]
Yeah it's a good idea, I just wanted to know the scope of this idea. I'll work on it when I get out of work. I would imagine it would be like:

- Projects can have a date field somehow
- If it's next wednesday highlight it

I'll have to find a way for that to work with the markdown syntax of the README file while also making it readable enough without the website.

Obviously if it gets too over-engineered I can always transfer to a config toml or json file but that's last resort.

I would love to have a forum using phpBB or Lemmy but we already have the discord server to discuss events so that would be out of scope for now.

**Comment by onelikeandidie** [comment]
Opened a branch for this, if you wanna try to bodge it in and PR, it would also be appreaciated
